---
# This playbook install some basic ubuntu packages

- name: install some basic ubuntu packages
  apt: pkg={{item}} state=present
  with_items:
    - autoconf
    - aptitude
    - ack-grep
    - byobu
    - cloc
    - cscope
    - curl
    - htop
    - nmap
    - nmon
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - texinfo
    - tig

# (HACK): Some linux distributions didn't provide a default .bashrc.
- name: ensure $HOME/.bashrc is present
  command: touch /home/{{whoami}}/.bashrc
